name: final_proj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  geolocator: ^10.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
